name: PR checks
on: pull_request

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: curl -X POST localhost:8080/hubot/canonicool-reminders-check

  run-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag webbot .

      - name: Run image
        run: |
          docker run -t -d --entrypoint bin/hubot --network host --env-file .env webbot
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8080/_status/check
